### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isTerminalOpen' of undefined

### ISSUE THREAD

**Issue by stacode123** [pfjarschel/atom-ipython-run#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ipython-run](https://github.com/pfjarschel/atom-ipython-run) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isTerminalOpen' of undefined

```
At C:\Users\dziob\.atom\packages\ipython-run\lib\ipython-run.coffee:119

TypeError: Cannot read property 'isTerminalOpen' of undefined
    at Object.isTerminalOpen (/packages/ipython-run/lib/ipython-run.coffee:119:43)
    at Object.runAction (/packages/ipython-run/lib/ipython-run.coffee:220:13)
    at Object.runFile (/packages/ipython-run/lib/ipython-run.coffee:247:8)
    at /packages/ipython-run/lib/ipython-run.coffee:74:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:718183)
    at EventEmitter.t (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:726106)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:39.1.0 core:move-up (input.hidden-input)
  4x -2:29.3.0 core:backspace (input.hidden-input)
     -2:19.3.0 core:confirm (input.hidden-input)
     -2:11.2.0 vk-terminal:new (input.hidden-input)
     -1:56.6.0 symbols-view:toggle-project-symbols (input.hidden-input)
     -1:54.3.0 core:confirm (input.hidden-input)
     -1:53 symbols-view:toggle-file-symbols (input.hidden-input)
     -1:51.8.0 core:backspace (input.hidden-input)
     -1:40.9.0 command-palette:toggle (input.hidden-input)
     -1:35.3.0 core:confirm (input.hidden-input)
     -1:35.3.0 window:run-benchmarks (input.hidden-input)
     -1:30.6.0 application:open-folder (input.hidden-input)
     -1:26 command-palette:toggle (input.hidden-input)
  4x -1:16.7.0 core:backspace (input.hidden-input)
     -1:06.1.0 welcome:show (input.hidden-input)
     -0:17.9.0 ipython-run:run-file (input.hidden-input)
```

### Non-Core Packages

```
ipython-run 0.3.0 
vk-terminal 3.0.1 
```

**Comment by D-u-c-k-s-e-l** [comment]
I had the same issue!

**Comment by iamsamratguha** [comment]
I am having the same issue after installing ipython-run package

**Comment by stacode123** [comment]
Kinnda stale
